-- ========================================================
-- BỔ SUNG KHO TỪ VỰNG PHONG PHÚ HSK 1 - HSK 6 CHO HANZIGO
-- ========================================================
USE HanziGoDB;
GO

-- 1. HSK 1: Bổ sung 35 từ vựng đời sống, số đếm, ăn uống, gia đình
INSERT INTO Words (Hanzi, Pinyin, MeaningVi, HskLevel, Topic, ExampleSentence, ExampleMeaningVi, AudioUrl) VALUES
(N'米饭', N'mǐ fàn', N'Cơm', 1, N'Ẩm thực', N'中国人喜欢吃米饭。', N'Người Trung Quốc thích ăn cơm.', N''),
(N'水', N'shuǐ', N'Nước', 1, N'Đồ uống', N'天气太热了，多喝水。', N'Thời tiết nóng quá, hãy uống nhiều nước.', N''),
(N'苹果', N'píng guǒ', N'Quả táo', 1, N'Hoa quả', N'桌子上有三个红苹果。', N'Trên bàn có ba quả táo đỏ.', N''),
(N'爸爸', N'bà ba', N'Bố, cha', 1, N'Gia đình', N'我爸爸是一名医生。', N'Bố tôi là một bác sĩ.', N''),
(N'妈妈', N'mā ma', N'Mẹ', 1, N'Gia đình', N'妈妈做的菜非常好吃。', N'Món ăn mẹ nấu rất ngon.', N''),
(N'儿子', N'ér zi', N'Con trai', 1, N'Gia đình', N'他的儿子正在上小学。', N'Con trai của anh ấy đang học tiểu học.', N''),
(N'女儿', N'nǚ ér', N'Con gái', 1, N'Gia đình', N'我女儿喜欢画画。', N'Con gái tôi thích vẽ tranh.', N''),
(N'今天', N'jīn tiān', N'Hôm nay', 1, N'Thời gian', N'今天的天气非常好。', N'Hôm nay thời tiết rất đẹp.', N''),
(N'明天', N'míng tiān', N'Ngày mai', 1, N'Thời gian', N'明天我们一起去学校。', N'Ngày mai chúng ta cùng nhau đến trường nhé.', N''),
(N'昨天', N'zuó tiān', N'Hôm qua', 1, N'Thời gian', N'昨天下午下雨了。', N'Chiều hôm qua trời đã đổ mưa.', N''),
(N'电脑', N'diàn nǎo', N'Máy vi tính', 1, N'Đồ dùng', N'我在电脑上查资料。', N'Tôi tra cứu tài liệu trên máy tính.', N''),
(N'电话', N'diàn huà', N'Điện thoại', 1, N'Liên lạc', N'请给我打个电话。', N'Xin hãy gọi điện thoại cho tôi.', N''),
(N'桌子', N'zhuō zi', N'Cái bàn', 1, N'Đồ đạc', N'书放在桌子上面。', N'Sách được đặt ở trên bàn.', N''),
(N'椅子', N'yǐ zi', N'Cái ghế', 1, N'Đồ đạc', N'请坐在这把椅子上。', N'Xin mời ngồi trên chiếc ghế này.', N''),
(N'猫', N'māo', N'Con mèo', 1, N'Động vật', N'这只小猫非常可爱。', N'Chú mèo con này rất dễ thương.', N''),
(N'狗', N'gǒu', N'Con chó', 1, N'Động vật', N'他家养了一只大狗。', N'Nhà anh ấy nuôi một chú chó lớn.', N''),
(N'喝', N'hē', N'Uống', 1, N'Hành động', N'你想喝茶还是喝咖啡？', N'Bạn muốn uống trà hay uống cà phê?', N''),
(N'吃', N'chī', N'Ăn', 1, N'Hành động', N'我们去吃中国菜吧。', N'Chúng mình đi ăn đồ ăn Trung Quốc đi.', N''),
(N'看', N'kàn', N'Nhìn, xem, đọc', 1, N'Hành động', N'我喜欢在晚上看书。', N'Tôi thích đọc sách vào ban đêm.', N''),
(N'听', N'tīng', N'Nghe', 1, N'Hành động', N'听音乐能让人放松。', N'Nghe nhạc có thể giúp con người thư giãn.', N''),
(N'说话', N'shuō huà', N'Nói chuyện', 1, N'Giao tiếp', N'请大家不要大声说话。', N'Xin mọi người đừng nói chuyện to tiếng.', N''),
(N'读', N'dú', N'Đọc', 1, N'Học tập', N'请大声读这段课文。', N'Xin hãy đọc to đoạn bài khóa này.', N''),
(N'写', N'xiě', N'Viết', 1, N'Học tập', N'他在纸上写了两个汉字。', N'Anh ấy viết hai chữ Hán lên tờ giấy.', N''),
(N'买', N'mǎi', N'Mua', 1, N'Mua sắm', N'我想买一本书。', N'Tôi muốn mua một quyển sách.', N''),
(N'钱', N'qián', N'Tiền', 1, N'Mua sắm', N'这件衣服多少钱？', N'Bộ quần áo này giá bao nhiêu tiền?', N''),
(N'多', N'duō', N'Nhiều', 1, N'Số lượng', N'图书馆里有很多书。', N'Trong thư viện có rất nhiều sách.', N''),
(N'少', N'shǎo', N'Ít', 1, N'Số lượng', N'他今天说的话很少。', N'Hôm nay anh ấy nói rất ít lời.', N''),
(N'大', N'dà', N'To, lớn', 1, N'Tính từ', N'这个苹果很大很甜。', N'Quả táo này rất to và rất ngọt.', N''),
(N'小', N'xiǎo', N'Nhỏ, bé', 1, N'Tính từ', N'我家有一间小房间。', N'Nhà tôi có một căn phòng nhỏ.', N''),
(N'冷', N'lěng', N'Lạnh', 1, N'Thời tiết', N'冬天的北京非常冷。', N'Mùa đông ở Bắc Kinh rất lạnh.', N''),
(N'热', N'rè', N'Nóng', 1, N'Thời tiết', N'夏天天气很热。', N'Mùa hè thời tiết rất nóng.', N''),
(N'高兴', N'gāo xìng', N'Vui vẻ', 1, N'Cảm xúc', N'认识你我很高兴。', N'Rất vui được làm quen với bạn.', N''),
(N'睡觉', N'shuì jiào', N'Đi ngủ', 1, N'Sinh hoạt', N'太晚了，早点睡觉吧。', N'Khuya quá rồi, hãy đi ngủ sớm đi.', N''),
(N'医院', N'yī yuàn', N'Bệnh viện', 1, N'Địa điểm', N'他身体不舒服，去医院了。', N'Người anh ấy không khỏe nên đã đến bệnh viện rồi.', N''),
(N'衣服', N'yī fu', N'Quần áo', 1, N'Đồ dùng', N'这件新衣服真好看。', N'Bộ quần áo mới này thật là đẹp.', N'');
GO

-- 2. HSK 2: Bổ sung 35 từ vựng giao tiếp, di chuyển, sức khỏe, màu sắc
INSERT INTO Words (Hanzi, Pinyin, MeaningVi, HskLevel, Topic, ExampleSentence, ExampleMeaningVi, AudioUrl) VALUES
(N'跑步', N'pǎo bù', N'Chạy bộ', 2, N'Thể thao', N'我每天早晨去公园跑步。', N'Mỗi buổi sáng tôi đều đến công viên chạy bộ.', N''),
(N'游泳', N'yóu yǒng', N'Bơi lội', 2, N'Thể thao', N'夏天我最喜欢游泳。', N'Mùa hè tôi thích nhất là đi bơi.', N''),
(N'打篮球', N'dǎ lán qiú', N'Chơi bóng rổ', 2, N'Thể thao', N'周末我们一起去打篮球吧。', N'Cuối tuần chúng mình cùng đi chơi bóng rổ nhé.', N''),
(N'唱歌', N'chàng gē', N'Ca hát', 2, N'Giải trí', N'妹妹唱歌唱得非常好听。', N'Em gái hát rất là hay.', N''),
(N'跳舞', N'tiào wǔ', N'Nhảy múa, khiêu vũ', 2, N'Giải trí', N'她从小就开始学跳舞。', N'Cô ấy từ nhỏ đã bắt đầu học múa.', N''),
(N'旅游', N'lǚ yóu', N'Du lịch', 2, N'Đời sống', N'今年假期我想去中国旅游。', N'Kỳ nghỉ năm nay tôi muốn đi du lịch Trung Quốc.', N''),
(N'飞机', N'fēi jī', N'Máy bay', 2, N'Giao thông', N'我们坐飞机去北京。', N'Chúng tôi đi máy bay đến Bắc Kinh.', N''),
(N'出租车', N'chū zū chē', N'Xe taxi', 2, N'Giao thông', N'下雨了，我们打出租车吧。', N'Trời mưa rồi, chúng mình bắt taxi thôi.', N''),
(N'公共汽车', N'gōng gòng qì chē', N'Xe buýt', 2, N'Giao thông', N'坐公共汽车很方便又便宜。', N'Đi xe buýt rất thuận tiện mà lại rẻ.', N''),
(N'火车站', N'huǒ chē zhàn', N'Ga tàu hỏa', 2, N'Giao thông', N'我家离火车站很近。', N'Nhà tôi cách ga tàu hỏa rất gần.', N''),
(N'生病', N'shēng bìng', N'Bị ốm, bị bệnh', 2, N'Sức khỏe', N'他最近生病了，在家里休息。', N'Dạo này anh ấy bị ốm nên đang nghỉ ngơi ở nhà.', N''),
(N'感冒', N'gǎn mào', N'Cảm cúm', 2, N'Sức khỏe', N'天气转凉了，小心感冒。', N'Thời tiết chuyển lạnh rồi, cẩn thận kẻo cảm cúm nhé.', N''),
(N'身体', N'shēn tǐ', N'Cơ thể, sức khỏe', 2, N'Sức khỏe', N'祝你身体健康，万事如意。', N'Chúc bạn dồi dào sức khỏe, vạn sự như ý.', N''),
(N'眼睛', N'yǎn jing', N'Mắt, đôi mắt', 2, N'Cơ thể', N'她的眼睛又大又亮。', N'Đôi mắt của cô ấy vừa to vừa sáng.', N''),
(N'晴天', N'qíng tiān', N'Trời nắng', 2, N'Thời tiết', N'明天是个晴天，适合出门。', N'Ngày mai là một ngày nắng đẹp, rất thích hợp ra ngoài.', N''),
(N'阴天', N'yīn tiān', N'Trời râm, nhiều mây', 2, N'Thời tiết', N'今天是阴天，好像要下雨。', N'Hôm nay trời râm, dường như sắp mưa.', N''),
(N'便宜', N'pián yi', N'Rẻ', 2, N'Mua sắm', N'超市里的水果挺便宜的。', N'Hoa quả trong siêu thị khá là rẻ.', N''),
(N'贵', N'guì', N'Đắt', 2, N'Mua sắm', N'这块手表太贵了，我买不起。', N'Chiếc đồng hồ này đắt quá, tôi không mua nổi.', N''),
(N'穿', N'chuān', N'Mặc, đi (giày dép)', 2, N'Sinh hoạt', N'出门要多穿点衣服。', N'Ra ngoài nhớ mặc thêm nhiều áo nhé.', N''),
(N'颜色', N'yán sè', N'Màu sắc', 2, N'Mô tả', N'你最喜欢什么颜色？', N'Bạn thích nhất là màu sắc nào?', N''),
(N'红色', N'hóng sè', N'Màu đỏ', 2, N'Màu sắc', N'过年的时候中国人喜欢穿红色。', N'Vào dịp năm mới người Trung Quốc thích mặc màu đỏ.', N''),
(N'黑色', N'hēi sè', N'Màu đen', 2, N'Màu sắc', N'他买了一辆黑色的自行车。', N'Anh ấy đã mua một chiếc xe đạp màu đen.', N''),
(N'白色', N'bái sè', N'Màu trắng', 2, N'Màu sắc', N'冬天大地上是一片白色。', N'Mùa đông khắp mặt đất phủ một màu trắng xóa.', N''),
(N'准备', N'zhǔn bèi', N'Chuẩn bị', 2, N'Hành động', N'我已经准备好参加考试了。', N'Tôi đã chuẩn bị sẵn sàng tham gia kỳ thi rồi.', N''),
(N'帮助', N'bāng zhù', N'Giúp đỡ', 2, N'Giao tiếp', N'非常感谢你在学习上的帮助。', N'Vô cùng cảm ơn sự giúp đỡ của bạn trong học tập.', N''),
(N'希望', N'xī wàng', N'Hy vọng', 2, N'Tâm lý', N'我希望能顺利通过HSK考试。', N'Tôi hy vọng có thể vượt qua kỳ thi HSK một cách thuận lợi.', N''),
(N'懂', N'dǒng', N'Hiểu', 2, N'Nhận thức', N'老师讲的内容我都听懂了。', N'Nội dung thầy giáo giảng tôi đều đã hiểu hết.', N''),
(N'错', N'cuò', N'Sai', 2, N'Đánh giá', N'这个问题你回答错了。', N'Câu hỏi này bạn trả lời sai rồi.', N''),
(N'对', N'duì', N'Đúng', 2, N'Đánh giá', N'你说得完全对。', N'Bạn nói hoàn toàn đúng.', N''),
(N'时间', N'shí jiān', N'Thời gian', 2, N'Khái niệm', N'时间过得真快，一年又过去了。', N'Thời gian trôi thật nhanh, một năm nữa lại qua đi.', N''),
(N'旁边', N'páng biān', N'Bên cạnh', 2, N'Phương vị', N'银行旁边有一家书店。', N'Bên cạnh ngân hàng có một hiệu sách.', N''),
(N'左边', N'zuǒ bian', N'Bên trái', 2, N'Phương vị', N'往前走，左边就是图书馆。', N'Đi thẳng về phía trước, bên tay trái chính là thư viện.', N''),
(N'右边', N'yòu bian', N'Bên phải', 2, N'Phương vị', N'洗手间在走廊的右边。', N'Nhà vệ sinh ở bên tay phải hành lang.', N''),
(N'西瓜', N'xī guā', N'Dưa hấu', 2, N'Hoa quả', N'夏天吃冰西瓜非常过瘾。', N'Mùa hè ăn dưa hấu ướp lạnh cực kỳ đã.', N''),
(N'鸡蛋', N'jī dàn', N'Trứng gà', 2, N'Ẩm thực', N'早上我吃了一个鸡蛋喝了牛奶。', N'Buổi sáng tôi ăn một quả trứng gà và uống sữa.', N'');
GO

-- 3. HSK 3: Bổ sung 35 từ vựng công việc, đời sống, du lịch, nhà hàng, cảm xúc
INSERT INTO Words (Hanzi, Pinyin, MeaningVi, HskLevel, Topic, ExampleSentence, ExampleMeaningVi, AudioUrl) VALUES
(N'经理', N'jīng lǐ', N'Giám đốc, quản lý', 3, N'Công việc', N'张经理正在会议室开会。', N'Giám đốc Trương đang họp trong phòng họp.', N''),
(N'同事', N'tóng shì', N'Đồng nghiệp', 3, N'Công việc', N'我和同事们相处得非常融洽。', N'Tôi và các đồng nghiệp chung sống rất hòa thuận.', N''),
(N'会议', N'huì yì', N'Cuộc họp', 3, N'Công việc', N'今天的会议讨论了新项目。', N'Cuộc họp hôm nay đã thảo luận về dự án mới.', N''),
(N'迟到', N'chí dào', N'Đến muộn', 3, N'Kỷ luật', N'路上堵车，所以我迟到了。', N'Tắc đường nên tôi đã đến muộn.', N''),
(N'请假', N'qǐng jià', N'Xin nghỉ phép', 3, N'Công việc', N'我身体不舒服，想请一天假。', N'Người tôi khó chịu, tôi muốn xin nghỉ phép một ngày.', N''),
(N'护照', N'hù zhào', N'Hộ chiếu', 3, N'Du lịch', N'出国前一定要检查护照的有效期。', N'Trước khi ra nước ngoài nhất định phải kiểm tra thời hạn hộ chiếu.', N''),
(N'行李', N'xíng li', N'Hành lý', 3, N'Du lịch', N'我的行李箱装满了衣服和特产。', N'Vali hành lý của tôi chứa đầy quần áo và đặc sản.', N''),
(N'宾馆', N'bīn guǎn', N'Khách sạn', 3, N'Du lịch', N'这家宾馆的服务态度非常好。', N'Thái độ phục vụ của khách sạn này rất tốt.', N''),
(N'信用卡', N'xìn yòng kǎ', N'Thẻ tín dụng', 3, N'Thanh toán', N'你可以用信用卡或者现金支付。', N'Bạn có thể thanh toán bằng thẻ tín dụng hoặc tiền mặt.', N''),
(N'菜单', N'cài dān', N'Thực đơn', 3, N'Nhà hàng', N'服务员，请拿一下菜单。', N'Phục vụ ơi, xin mang giúp tôi cuốn thực đơn.', N''),
(N'饮料', N'yǐn liào', N'Đồ uống', 3, N'Ẩm thực', N'饭后喝一杯热饮料很舒服。', N'Sau bữa ăn uống một ly đồ uống nóng rất dễ chịu.', N''),
(N'筷子', N'kuài zi', N'Đôi đũa', 3, N'Ẩm thực', N'很多外国人学会了用筷子吃饭。', N'Rất nhiều người nước ngoài đã học được cách dùng đũa ăn cơm.', N''),
(N'尝', N'cháng', N'Nếm thử', 3, N'Ẩm thực', N'你尝尝这道菜，味道怎么样？', N'Bạn nếm thử món ăn này xem mùi vị thế nào?', N''),
(N'满意', N'mǎn yì', N'Hài lòng', 3, N'Cảm xúc', N'客户对我们的方案非常满意。', N'Khách hàng rất hài lòng với phương án của chúng tôi.', N''),
(N'习惯', N'xí guàn', N'Thói quen, quen với', 3, N'Đời sống', N'早睡早起是一个好习惯。', N'Ngủ sớm dậy sớm là một thói quen tốt.', N''),
(N'热情', N'rè qíng', N'Nhiệt tình', 3, N'Tính cách', N'这里的人民非常热情友好。', N'Người dân ở đây rất nhiệt tình và hiếu khách.', N''),
(N'照顾', N'zhào gù', N'Chăm sóc', 3, N'Hành động', N'生病的时候妈妈一直细心照顾我。', N'Lúc bị ốm mẹ luôn tận tình chăm sóc tôi.', N''),
(N'参加', N'cān jiā', N'Tham gia', 3, N'Hoạt động', N'明天我要参加汉语演讲比赛。', N'Ngày mai tôi sẽ tham gia cuộc thi diễn thuyết tiếng Trung.', N''),
(N'影响', N'yǐng xiǎng', N'Ảnh hưởng', 3, N'Tác động', N'睡眠不足会影响第二天的学习。', N'Thiếu ngủ sẽ ảnh hưởng đến việc học tập của ngày hôm sau.', N''),
(N'解决', N'jiě jué', N'Giải quyết', 3, N'Hành động', N'我们终于找到了解决问题的方法。', N'Chúng tôi cuối cùng đã tìm ra phương pháp giải quyết vấn đề.', N''),
(N'遇到', N'yù dào', N'Gặp phải', 3, N'Trải nghiệm', N'在生活中遇到困难不要放弃。', N'Trong cuộc sống gặp phải khó khăn đừng từ bỏ.', N''),
(N'检查', N'jiǎn chá', N'Kiểm tra', 3, N'Hành động', N'交卷前请仔细检查一遍答案。', N'Trước khi nộp bài hãy kiểm tra kỹ đáp án một lần.', N''),
(N'清楚', N'qīng chu', N'Rõ ràng', 3, N'Nhận thức', N'请把你的想法说清楚一点。', N'Xin hãy nói rõ ràng hơn suy nghĩ của bạn.', N''),
(N'简单', N'jiǎn dān', N'Đơn giản', 3, N'Đánh giá', N'这道数学题其实很简单。', N'Bài toán này thực ra rất đơn giản.', N''),
(N'认真', N'rèn zhēn', N'Nghiêm túc, chăm chỉ', 3, N'Thái độ', N'他对待每一份工作都很认真。', N'Anh ấy đối với mỗi công việc đều rất nghiêm túc.', N''),
(N'奇怪', N'qí guài', N'Kỳ lạ', 3, N'Cảm nhận', N'今天的天气有些奇怪，忽冷忽热。', N'Thời tiết hôm nay có chút kỳ lạ, lúc nóng lúc lạnh.', N''),
(N'害怕', N'hài pà', N'Sợ hãi', 3, N'Cảm xúc', N'别害怕，有大家在这里陪你。', N'Đừng sợ hãi, có mọi người ở đây đồng hành cùng bạn.', N''),
(N'生气', N'shēng qì', N'Tức giận', 3, N'Cảm xúc', N'遇到分歧要冷静，不要轻易生气。', N'Gặp phải bất đồng cần bình tĩnh, không nên dễ dàng tức giận.', N''),
(N'难过', N'nán guò', N'Buồn rầu, đau lòng', 3, N'Cảm xúc', N'听到这个坏消息大家都很难过。', N'Nghe được tin buồn này mọi người đều rất đau lòng.', N''),
(N'祝贺', N'zhù hè', N'Chúc mừng', 3, N'Giao tiếp', N'热烈祝贺你顺利毕业！', N'Nhiệt liệt chúc mừng bạn tốt nghiệp thuận lợi!', N''),
(N'历史', N'lì shǐ', N'Lịch sử', 3, N'Khoa học', N'中国有几千年的悠久历史。', N'Trung Quốc có lịch sử lâu đời mấy nghìn năm.', N''),
(N'文化', N'wén huà', N'Văn hóa', 3, N'Khoa học', N'了解不同的文化能开阔视野。', N'Tìm hiểu những nền văn hóa khác nhau có thể mở rộng tầm nhìn.', N''),
(N'环境', N'huán jìng', N'Môi trường', 3, N'Môi trường', N'保护环境是我们每个人的责任。', N'Bảo vệ môi trường là trách nhiệm của mỗi người chúng ta.', N''),
(N'不但', N'bú dàn', N'Không những', 3, N'Liên từ', N'他不但聪明，而且非常勤奋。', N'Anh ấy không những thông minh mà còn rất cần cù.', N''),
(N'而且', N'ér qiě', N'Mà còn', 3, N'Liên từ', N'这本书不仅有趣，而且很有启发。', N'Cuốn sách này không chỉ thú vị mà còn rất gợi mở.', N'');
GO

-- 4. HSK 4: Bổ sung 35 từ vựng công nghệ, phỏng vấn, kinh doanh, tâm lý, đời sống
INSERT INTO Words (Hanzi, Pinyin, MeaningVi, HskLevel, Topic, ExampleSentence, ExampleMeaningVi, AudioUrl) VALUES
(N'简历', N'jiǎn lì', N'Sơ yếu lý lịch, CV', 4, N'Tuyển dụng', N'面试前请准备一份详细的简历。', N'Trước khi phỏng vấn xin hãy chuẩn bị một bản CV chi tiết.', N''),
(N'面试', N'miàn shì', N'Phỏng vấn', 4, N'Tuyển dụng', N'他昨天的求职面试非常成功。', N'Buổi phỏng vấn xin việc hôm qua của anh ấy rất thành công.', N''),
(N'录取', N'lù qǔ', N'Trúng tuyển, tuyển chọn', 4, N'Tuyển dụng', N'恭喜你被知名大学录取了！', N'Chúc mừng bạn đã trúng tuyển vào trường đại học danh tiếng!', N''),
(N'薪水', N'xīn shuǐ', N'Tiền lương', 4, N'Công việc', N'这家公司的福利好，薪水也很可观。', N'Phúc lợi công ty này tốt, tiền lương cũng rất tương xứng.', N''),
(N'压力', N'yā lì', N'Áp lực', 4, N'Tâm lý', N'现代人在工作中常常面临很大压力。', N'Người hiện đại trong công việc thường đối mặt áp lực lớn.', N''),
(N'竞争', N'jìng zhēng', N'Cạnh tranh', 4, N'Kinh tế', N'市场竞争越来越激烈。', N'Sự cạnh tranh trên thị trường ngày càng khốc liệt.', N''),
(N'互联网', N'hù lián wǎng', N'Mạng Internet', 4, N'Công nghệ', N'互联网彻底改变了人们的生活方式。', N'Mạng Internet đã thay đổi triệt để lối sống của con người.', N''),
(N'发展', N'fā zhǎn', N'Phát triển', 4, N'Kinh tế', N'随着科技的发展，生活越来越便利。', N'Cùng với sự phát triển của khoa học, cuộc sống ngày càng tiện lợi.', N''),
(N'经济', N'jīng jì', N'Kinh tế', 4, N'Kinh tế', N'这个城市的经济发展速度非常快。', N'Tốc độ phát triển kinh tế của thành phố này rất nhanh.', N''),
(N'投资', N'tóu zī', N'Đầu tư', 4, N'Tài chính', N'投资有风险，决策需谨慎。', N'Đầu tư luôn có rủi ro, ra quyết định cần thận trọng.', N''),
(N'法律', N'fǎ lǜ', N'Pháp luật', 4, N'Xã hội', N'每个人都必须遵守国家的法律。', N'Mỗi người đều phải tuân thủ pháp luật của quốc gia.', N''),
(N'诚实', N'chéng shí', N'Thành thật', 4, N'Phẩm chất', N'诚实是做人最重要的品质之一。', N'Thành thật là một trong những phẩm chất quan trọng nhất làm người.', N''),
(N'礼貌', N'lǐ mào', N'Lịch sự, lễ phép', 4, N'Giao tiếp', N'对待长辈要讲礼貌。', N'Đối xử với người lớn tuổi phải biết giữ lễ phép.', N''),
(N'幽默', N'yōu mò', N'Hài hước', 4, N'Tính cách', N'他是一个非常幽默的人，总是逗大家笑。', N'Anh ấy là người rất hài hước, luôn chọc mọi người cười.', N''),
(N'骄傲', N'jiāo ào', N'Tự hào, kiêu ngạo', 4, N'Cảm xúc', N'父母为你取得的成就感到无比骄傲。', N'Bố mẹ cảm thấy vô cùng tự hào về thành tựu của con.', N''),
(N'鼓励', N'gǔ lì', N'Khuyến khích, động viên', 4, N'Tâm lý', N'老师的鼓励给了我很大的勇气。', N'Sự động viên của cô giáo đã tiếp thêm cho tôi nhiều dũng khí.', N''),
(N'坚持', N'jiān chí', N'Kiên trì', 4, N'Phẩm chất', N'只要坚持下去，就一定能看到希望。', N'Chỉ cần kiên trì đến cùng, nhất định sẽ nhìn thấy hy vọng.', N''),
(N'适应', N'shì yìng', N'Thích nghi', 4, N'Hành vi', N'来到新的环境需要一定的时间去适应。', N'Đến môi trường mới cần một khoảng thời gian nhất định để thích nghi.', N''),
(N'丰富', N'fēng fù', N'Phong phú', 4, N'Tính từ', N'课外活动极大地丰富了校园生活。', N'Các hoạt động ngoại khóa làm phong phú thêm đời sống học đường.', N''),
(N'深刻', N'shēn kè', N'Sâu sắc', 4, N'Đánh giá', N'这篇课文给我留下了深刻的印象。', N'Bài khóa này đã để lại trong tôi ấn tượng vô cùng sâu sắc.', N''),
(N'严格', N'yán gé', N'Nghiêm khắc', 4, N'Thái độ', N'教练对运动员的要求非常严格。', N'Huấn luyện viên đặt ra yêu cầu rất nghiêm khắc với vận động viên.', N''),
(N'尽管', N'jǐn guǎn', N'Mặc dù', 4, N'Liên từ', N'尽管天空中飘着大雨，但他依然准时赴约。', N'Mặc dù trời mưa to, anh ấy vẫn đến điểm hẹn đúng giờ.', N''),
(N'无论', N'wú lùn', N'Bất luận, dù cho', 4, N'Liên từ', N'无论遇到什么风雨，我们都要勇往直前。', N'Bất luận gặp phải sóng gió gì, chúng ta đều phải dũng cảm tiến lên.', N''),
(N'顺便', N'shùn biàn', N'Tiện thể, nhân tiện', 4, N'Phó từ', N'你出门的时候顺便帮我寄封信吧。', N'Lúc bạn ra ngoài tiện thể gửi giúp tôi bức thư nhé.', N''),
(N'果然', N'guǒ rán', N'Quả nhiên', 4, N'Phó từ', N'天气预报说今天有雪，果然下雪了。', N'Dự báo thời tiết nói hôm nay có tuyết, quả nhiên tuyết rơi thật.', N''),
(N'即使', N'jí shǐ', N'Cho dù, ngay cả khi', 4, N'Liên từ', N'即使失败了，也是一次宝贵的经验。', N'Cho dù thất bại thì đó cũng là một bài học kinh nghiệm quý giá.', N''),
(N'既然', N'jì rán', N'Đã... thì', 4, N'Liên từ', N'既然决定了，就要全力以赴做好。', N'Một khi đã quyết định thì phải dốc toàn lực làm cho tốt.', N''),
(N'偶尔', N'ǒu ěr', N'Thỉnh thoảng, ngẫu nhiên', 4, N'Phó từ', N'工作很忙，我只能偶尔抽空去健身。', N'Công việc bận rộn, tôi chỉ thỉnh thoảng mới tranh thủ đi tập gym.', N''),
(N'究竟', N'jiū jìng', N'Rốt cuộc', 4, N'Phó từ', N'你究竟去不去？请给我一个明确的答复。', N'Rốt cuộc bạn có đi hay không? Xin cho tôi câu trả lời rõ ràng.', N''),
(N'千万', N'qiān wàn', N'Nhất thiết, vạn lần', 4, N'Phó từ', N'过马路千万要看红绿灯。', N'Qua đường nhất thiết phải chú ý nhìn đèn giao thông.', N''),
(N'专门', N'zhuān mén', N'Chuyên môn, đặc biệt', 4, N'Phó từ', N'这是专门为你准备的生日礼物。', N'Đây là món quà sinh nhật được chuẩn bị riêng dành tặng bạn.', N''),
(N'详细', N'xiáng xì', N'Chi tiết', 4, N'Tính từ', N'请为我们详细介绍一下这款新产品。', N'Xin hãy giới thiệu chi tiết cho chúng tôi về sản phẩm mới này.', N''),
(N'精彩', N'jīng cǎi', N'Đặc sắc, tuyệt vời', 4, N'Đánh giá', N'昨晚的足球比赛非常精彩。', N'Trận thi đấu bóng đá tối qua vô cùng đặc sắc kịch tính.', N''),
(N'著名', N'zhù míng', N'Nổi tiếng', 4, N'Tính từ', N'北京故宫是世界上著名的古建筑群。', N'Tử Cấm Thành Bắc Kinh là quần thể kiến trúc cổ nổi tiếng thế giới.', N''),
(N'轻松', N'qīng sōng', N'Thư thái, thoải mái', 4, N'Cảm xúc', N'听听轻音乐能让人感到心情轻松。', N'Nghe một bản nhạc nhẹ có thể làm lòng người thư thái thoải mái.', N'');
GO

-- 5. HSK 5: Bổ sung 30 từ vựng chuyên sâu, thành ngữ 4 chữ, kinh tế, xã hội
INSERT INTO Words (Hanzi, Pinyin, MeaningVi, HskLevel, Topic, ExampleSentence, ExampleMeaningVi, AudioUrl) VALUES
(N'入乡随俗', N'rù xiāng suí sú', N'Nhập gia tùy tục', 5, N'Thành ngữ', N'到了国外生活，首先要学会入乡随俗。', N'Đến nước ngoài sinh sống, trước tiên phải học cách nhập gia tùy tục.', N''),
(N'拔苗助长', N'bá miáo zhù zhǎng', N'Dục tốc bất đạt, ép chín sớm', 5, N'Thành ngữ', N'教育孩子不能拔苗助长，要顺其自然。', N'Giáo dục con trẻ chớ nóng vội dục tốc bất đạt, cần thuận theo tự nhiên.', N''),
(N'半途而废', N'bàn tú ér fèi', N'Bỏ dở nửa chừng', 5, N'Thành ngữ', N'做事情最忌讳半途而废，贵在持之以恒。', N'Làm việc kiêng kỵ nhất là bỏ dở giữa chừng, quý ở chỗ kiên trì bền bỉ.', N''),
(N'自由自在', N'zì yóu zì zài', N'Tự do tự tại', 5, N'Thành ngữ', N'鸟儿在天空中自由自在地飞翔。', N'Những chú chim tung cánh bay lượn tự do tự tại trên bầu trời.', N''),
(N'井底之蛙', N'jǐng dǐ zhī wā', N'Ếch ngồi đáy giếng', 5, N'Thành ngữ', N'不走出门开阔眼界，很容易成为井底之蛙。', N'Không bước ra ngoài mở mang tầm mắt rất dễ trở thành ếch ngồi đáy giếng.', N''),
(N'莫名其妙', N'mò míng qí miào', N'Kỳ lạ khó hiểu', 5, N'Thành ngữ', N'他今天突然发脾气，真让人感到莫名其妙。', N'Hôm nay anh ấy bỗng nổi cơn thịnh nộ, thật khiến người ta khó hiểu.', N''),
(N'迫不及待', N'pò bù jí dài', N'Nóng lòng không thể chờ', 5, N'Thành ngữ', N'一收到包裹，他就迫不及待地打开了。', N'Vừa nhận được kiện hàng, cậu ấy liền nóng lòng mở ra ngay.', N''),
(N'讨价还价', N'tǎo jià huán jià', N'Mặc cả, trả giá', 5, N'Thương mại', N'在传统集市买东西通常可以适当讨价还价。', N'Mua đồ ở các khu chợ truyền thống thường có thể mặc cả giá cả.', N''),
(N'滔滔不绝', N'tāo tāo bù jué', N'Nói thao thao bất tuyệt', 5, N'Thành ngữ', N'一谈到他喜爱的专业，他就滔滔不绝地说个不停。', N'Hễ nhắc đến chuyên môn yêu thích, anh ấy liền thao thao bất tuyệt nói không dứt.', N''),
(N'采访', N'cǎi fǎng', N'Phỏng vấn (báo chí)', 5, N'Truyền thông', N'记者正在对获奖科学家进行现场采访。', N'Nhà báo đang tiến hành phỏng vấn trực tiếp nhà khoa học đoạt giải.', N''),
(N'报告', N'bào gào', N'Báo cáo', 5, N'Công việc', N'他在会上作了关于年度业绩的详尽报告。', N'Anh ấy đã trình bày báo cáo chi tiết về thành tích năm trong hội nghị.', N''),
(N'消费', N'xiāo fèi', N'Tiêu dùng', 5, N'Kinh tế', N'随着收入提高，居民的消费水平显著改善。', N'Cùng với thu nhập nâng cao, mức tiêu dùng của người dân cải thiện rõ rệt.', N''),
(N'资源', N'zī yuán', N'Tài nguyên', 5, N'Môi trường', N'水和森林是人类赖以生存的宝贵资源。', N'Nước và rừng là nguồn tài nguyên quý giá để loài người sinh tồn.', N''),
(N'效率', N'xiào lǜ', N'Hiệu suất, hiệu quả', 5, N'Công việc', N'采用智能化工具可以大幅提升工作效率。', N'Áp dụng công cụ thông minh có thể nâng cao vượt bậc hiệu suất làm việc.', N''),
(N'趋势', N'qū shì', N'Xu hướng, trào lưu', 5, N'Phân tích', N'绿色低碳已成为全球产业发展的必然趋势。', N'Xanh hóa và giảm phát thải carbon đã trở thành xu thế tất yếu toàn cầu.', N''),
(N'政策', N'zhèng cè', N'Chính sách', 5, N'Chính trị', N'政府出台了许多扶持创业创新的优惠政策。', N'Chính phủ đã ban hành nhiều chính sách ưu đãi nhằm hỗ trợ khởi nghiệp đổi mới.', N''),
(N'挑战', N'tiǎo zhàn', N'Thách thức', 5, N'Đời sống', N'面对未来的挑战，我们要充满信心。', N'Đối diện trước những thách thức tương lai, chúng ta cần tràn đầy niềm tin.', N''),
(N'核心', N'hé xīn', N'Cốt lõi, trọng tâm', 5, N'Khái niệm', N'创新是企业保持长期竞争力的核心力量。', N'Đổi mới sáng tạo là sức mạnh cốt lõi giúp doanh nghiệp duy trì sức cạnh tranh.', N''),
(N'谨慎', N'jǐn shèn', N'Thận trọng', 5, N'Tính cách', N'在签署合同之前必须进行谨慎的法律审查。', N'Trước khi ký kết hợp đồng bắt buộc phải tiến hành rà soát pháp lý thận trọng.', N''),
(N'谦虚', N'qiān xū', N'Khiêm tốn', 5, N'Phẩm chất', N'谦虚使人进步，骄傲使人落后。', N'Khiêm tốn giúp người ta tiến bộ, kiêu ngạo làm người ta tụt lùi.', N''),
(N'甚至', N'shèn zhì', N'Thậm chí', 5, N'Phó từ', N'他太专注工作了，甚至忘记了吃午饭。', N'Anh ấy quá mải mê làm việc, thậm chí còn quên cả ăn bữa trưa.', N''),
(N'反而', N'fǎn ér', N'Trái lại, ngược lại', 5, N'Liên từ', N'这次失败不仅没让他沮丧，反而激发了他的斗志。', N'Thất bại lần này chẳng những không làm anh ấy nản lòng mà trái lại còn kích thích ý chí.', N''),
(N'毕竟', N'bì jìng', N'Dù sao thì, rốt cuộc', 5, N'Phó từ', N'他年纪毕竟还小，难免会犯一些错误。', N'Dù sao thì nó tuổi đời còn nhỏ, khó tránh khỏi mắc phải vài sai lầm.', N''),
(N'悄悄', N'qiāo qiāo', N'Lặng lẽ, nhẹ nhàng', 5, N'Phó từ', N'春风悄悄地吹绿了大江南北。', N'Cơn gió xuân lặng lẽ thổi màu xanh biếc khắp hai bờ sông bến nước.', N''),
(N'格外', N'gé wài', N'Đặc biệt, khác thường', 5, N'Phó từ', N'雨后的空气闻起来显得格外清新。', N'Bầu không khí sau cơn mưa ngửi thấy trong lành khác thường.', N''),
(N'何必', N'hé bì', N'Hà tất, việc gì phải', 5, N'Phó từ', N'都是好朋友，何必为了小事伤了和气。', N'Đều là bạn bè tốt của nhau, hà tất vì chuyện cỏn con mà mất đi hòa khí.', N''),
(N'索性', N'suǒ xìng', N'Thà rằng, dứt khoát', 5, N'Phó từ', N'既然雨下得这么大，我们索性改天再出发吧。', N'Mưa đã trút xuống xối xả như thế, ta dứt khoát dời sang ngày khác hẵng lên đường.', N''),
(N'未免', N'wèi miǎn', N'E rằng, khó tránh khỏi', 5, N'Phó từ', N'你这样毫无根据地下结论，未免有些草率。', N'Cậu hạ kết luận thiếu căn cứ như vậy e rằng có phần hấp tấp qua loa.', N''),
(N'总而言之', N'zǒng ér yán zhī', N'Tóm lại, nói tóm lại', 5, N'Liên từ', N'总而言之，只要我们齐心协力，困难总会迎刃而解。', N'Tóm lại, chỉ cần chúng ta đồng lòng hiệp lực, khó khăn ắt sẽ được hóa giải.', N''),
(N'恍然大悟', N'huǎng rán dà wù', N'Bừng tỉnh ngộ ra', 5, N'Thành ngữ', N'经老师一点拨，我这才恍然大悟。', N'Được thầy chỉ bảo một chút, bấy giờ tôi mới bừng tỉnh ngộ ra.', N'');
GO

-- 6. HSK 6: Bổ sung 30 từ vựng cao cấp, thành ngữ kinh điển, triết học, học thuật
INSERT INTO Words (Hanzi, Pinyin, MeaningVi, HskLevel, Topic, ExampleSentence, ExampleMeaningVi, AudioUrl) VALUES
(N'画蛇添足', N'huà shé tiān zú', N'Vẽ rắn thêm chân (thừa thãi)', 6, N'Thành ngữ', N'文章写得恰到好处，无需再做画蛇添足的修饰。', N'Bài văn viết chuẩn xác vừa khéo, chẳng cần điểm xuyết vẽ rắn thêm chân.', N''),
(N'狐假虎威', N'hú jiǎ hǔ wēi', N'Cáo mượn oai hùm', 6, N'Thành ngữ', N'他仗着领导的权力狐假虎威，大家都很反感。', N'Anh ta cậy quyền của cấp trên cáo mượn oai hùm, khiến ai nấy đều phản cảm.', N''),
(N'卧薪尝胆', N'wò xīn cháng dǎn', N'Nằm gai nếm mật', 6, N'Thành ngữ', N'经过十年的卧薪尝胆，他的公司终于在行业中崛起。', N'Trải qua mười năm nằm gai nếm mật, công ty của anh ấy rốt cuộc đã trỗi dậy.', N''),
(N'纸上谈兵', N'zhǐ shàng tán bīng', N'Nói suông trên giấy, lý thuyết suông', 6, N'Thành ngữ', N'搞科研不能光是纸上谈兵，必须结合实践验证。', N'Nghiên cứu khoa học không thể nói suông trên giấy, bắt buộc phải kết hợp thực tiễn kiểm nghiệm.', N''),
(N'掩耳盗铃', N'yǎn ěr dào líng', N'Bịt tai trộm chuông, tự lừa dối mình', 6, N'Thành ngữ', N'明知有问题却不承认，这无异于掩耳盗铃。', N'Biết rõ có sai phạm nhưng không thừa nhận, điều này chẳng khác nào bịt tai trộm chuông.', N''),
(N'举世闻名', N'jǔ shì wén míng', N'Nổi tiếng khắp thế giới', 6, N'Thành ngữ', N'万里长城是一处举世闻名的伟大奇迹。', N'Vạn Lý Trường Thành là một kỳ quan vĩ đại nổi tiếng khắp thế giới.', N''),
(N'潜移默化', N'qián yí mò huà', N'Mưa dầm thấm lâu, thẩm thấu dần', 6, N'Thành ngữ', N'良好的家庭氛围对孩子的性格产生着潜移默化的影响。', N'Bầu không khí gia đình lành mạnh sẽ thẩm thấu dần dần vào tính cách của trẻ.', N''),
(N'循序渐进', N'xún xù jiàn jìn', N'Tuần tự từng bước, tiệm tiến', 6, N'Thành ngữ', N'学习外语是一个循序渐进的过程，切忌急于求成。', N'Học ngoại ngữ là một tiến trình tuần tự từng bước, tránh nóng vội đốt cháy giai đoạn.', N''),
(N'络绎不绝', N'luò yì bù jué', N'Nối liền không ngớt, nườm nượp', 6, N'Thành ngữ', N'假期期间，来到这里参观景点的游客络绎不绝。', N'Kỳ nghỉ lễ, lượng du khách đến tham quan thắng cảnh nườm nượp nối dài không dứt.', N''),
(N'突飞猛进', N'tū fēi měng jìn', N'Tiến bộ vượt bậc, phát triển vũ bão', 6, N'Thành ngữ', N'近年来，人工智能技术取得了突飞猛进的发展。', N'Những năm gần đây, công nghệ AI đã đạt được những bước tiến vượt bậc vũ bão.', N''),
(N'宏观', N'hóng guān', N'Vĩ mô', 6, N'Học thuật', N'我们需要从宏观的视角审视整个产业的转型方向。', N'Chúng ta cần nhìn nhận định hướng chuyển đổi toàn ngành từ góc nhìn vĩ mô.', N''),
(N'微观', N'wēi guān', N'Vi mô', 6, N'Học thuật', N'科学家们利用电子显微镜观察物质的微观结构。', N'Các nhà khoa học sử dụng kính hiển vi điện tử quan sát cấu trúc vi mô của vật chất.', N''),
(N'战略', N'zhàn lüè', N'Chiến lược', 6, N'Quản trị', N'制定清晰的发展战略是企业立于不败之地的基石。', N'Hoạch định chiến lược phát triển sáng suốt là nền móng giúp doanh nghiệp đứng vững.', N''),
(N'决策', N'jué cè', N'Quyết sách, đưa ra quyết định', 6, N'Quản trị', N'重大投资必须经过严谨的论证后再行决策。', N'Các khoản đầu tư trọng điểm bắt buộc phải trải qua lập luận chặt chẽ rồi mới ra quyết sách.', N''),
(N'逻辑', N'luó ji', N'Logic, lý lẽ', 6, N'Triết học', N'这篇学术论文结构严密，论证逻辑十分清晰。', N'Bài luận văn học thuật này có bố cục chặt chẽ, tư duy lập luận hết sức mạch lạc.', N''),
(N'哲学', N'zhé xué', N'Triết học', 6, N'Triết học', N'哲学探寻的是关于世界本原与人生价值的深层思考。', N'Triết học truy tìm những suy tư tầng sâu về bản nguyên thế giới và giá trị kiếp người.', N''),
(N'阐述', N'chǎn shù', N'Trình bày, luận giải', 6, N'Học thuật', N'作者在书中深入阐述了经济周期波动的内在机理。', N'Tác giả trong cuốn sách đã luận giải sâu sắc cơ chế nội tại của chu kỳ kinh tế.', N''),
(N'衡量', N'héng liáng', N'Cân đo, đong đếm, đánh giá', 6, N'Hành động', N'不能单凭分数来衡量一个学生的综合潜能。', N'Không thể đơn thuần dựa vào điểm số để cân đo năng lực tiềm tàng của một học sinh.', N''),
(N'抵制', N'dǐ zhì', N'Bài trừ, tẩy chay, chống lại', 6, N'Xã hội', N'全社会都应该坚决抵制虚假不良广告的泛滥。', N'Toàn xã hội cần phải kiên quyết bài trừ vấn nạn quảng cáo sai sự thật tràn lan.', N''),
(N'淘汰', N'táo tài', N'Đào thải', 6, N'Quy luật', N'落后的技术终将被更先进、更高效的创新所淘汰。', N'Công nghệ lạc hậu cuối cùng cũng sẽ bị đào thải bởi các cải tiến tiên tiến hơn.', N''),
(N'凝聚', N'níng jù', N'Ngưng tụ, gắn kết, kết tinh', 6, N'Xã hội', N'这项工程凝聚了数千名建设者夜以继日的汗水。', N'Công trình thế kỷ này kết tinh mồ hôi đêm ngày của hàng nghìn con người kiến thiết.', N''),
(N'渊博', N'yuān bó', N'Uyên bác', 6, N'Phẩm chất', N'这位老教授学识渊博，深受全体师生的尊敬。', N'Vị giáo sư lão thành này học thức uyên bác, được toàn thể thầy trò hết lòng kính trọng.', N''),
(N'卓越', N'zhuó yuè', N'Xuất sắc, lỗi lạc', 6, N'Đánh giá', N'他凭借卓越的领导才能带领团队战胜了重重险阻。', N'Bằng tài lãnh đạo kiệt xuất, anh ấy đã dẫn dắt đội ngũ vượt qua muôn vàn trắc trở.', N''),
(N'毋庸置疑', N'wú yōng zhì yí', N'Không còn nghi ngờ gì nữa', 6, N'Thành ngữ', N'他在该领域的权威地位是毋庸置疑的。', N'Địa vị chuyên môn của ông ấy trong lĩnh vực này là điều không thể nghi ngờ.', N''),
(N'持之以恒', N'chí zhī yǐ héng', N'Kiên trì bền bỉ', 6, N'Thành ngữ', N'凡事唯有持之以恒，方能达到登峰造极的境界。', N'Phàm làm việc gì chỉ có kiên trì bền bỉ mới đạt tới cảnh giới tột đỉnh vinh quang.', N''),
(N'实事求是', N'shí shì qiú shì', N'Thực sự cầu thị', 6, N'Thành ngữ', N'我们要坚持实事求是的科学态度，严谨对待每一次实验。', N'Chúng ta cần giữ vững thái độ khoa học thực sự cầu thị, nghiêm cẩn với từng thí nghiệm.', N''),
(N'未雨绸缪', N'wèi yǔ chóu móu', N'Lo trước tính sau, phòng bệnh hơn chữa bệnh', 6, N'Thành ngữ', N'面对未来的金融波动，各机构都应未雨绸缪做好储备。', N'Trước những biến động tài chính tương lai, các cơ quan đều cần lo trước tính sau chuẩn bị.', N''),
(N'一视同仁', N'yī shì tóng rén', N'Đối xử bình đẳng, không thiên vị', 6, N'Thành ngữ', N'优秀的管理者对待所有员工都应该一视同仁。', N'Người quản trị ưu tú đối với mọi nhân viên đều phải bình đẳng công tâm.', N''),
(N'不约而同', N'bù yuē ér tóng', N'Không hẹn mà gặp, cùng chung suy nghĩ', 6, N'Thành ngữ', N'听到精彩之处，台下观众不约而同地鼓起掌来。', N'Nghe đến đoạn cao trào, khán giả dưới khán đài không hẹn mà cùng vỗ tay tán thưởng.', N''),
(N'脍炙人口', N'kuài zhì rén kǒu', N'Say đắm lòng người, truyền tụng rộng rãi', 6, N'Thành ngữ', N'李白的这首诗千百年来一直是脍炙人口的佳作。', N'Bài thơ này của Lý Bạch ngàn năm qua vẫn là áng thi ca say đắm lòng người.', N'');
GO
